services:
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        depends_on:
            - mongo

    mongo:
        image: mongo:5
        container_name: jwt_auth_mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
